api/zapi_unix.go
api/zapi_windows.go
column.go

Runtime Error:- CGO argument has GoPointer to GoPointer at SQLBindCol has been fixed

GoPointer to GoPointer Fixed

---

API_DOCUMENTATION.md

I had problems reading the API documentation so I've indented it correctly.

Properly indent example code to make it more readable.

---

api/api_unix.go
api/api_windows.go
column.go

XML datatype support

---

column.go

Send size of LONG VARCHAR

---

column.go

Set 1 to default year, month and day SQL_C_TYPE_TIME

---

param.go

Don't get pointer of inexistent index when data is empty binding []byte

---

api/api_unix.go
api/zapi_unix.go

Toward issue - https://github.com/ibmdb/go_ibm_db/issues/95
Added AIX CGO support

AIX support for go_ibm_db

---

installer/setup.go

https://github.com/ibmdb/go_ibm_db/issues/107
AIX is different with Linux, I found if using AIX to unzipping xxx.tar.gz.
we should ：
1. gunzip xxx.tgz
2. xxx.tgz will be converted to xxx.tar
3. tar -xvf xxx.tar 
So open this PR to fix unzip clidriver.tar.gz error on AIX.
@akhilravuri1 Please help review and merge code. Thanks!

setup.go support AIX.

---

API_DOCUMENTATION.md
README.md

All example code has been run through `gofmt`. I fixed a couple of small typos while I was at it but did not make any changes to the actual code.
Fixes #113 
DCO 1.1 Signed-off-by: David Mooney pez@vex.net

Format sample code in README and API_DOCUMENTATION using go fmt

---

conn.go

Propose solution for parametrized queries

---

README.md
column.go

Updated export LD_LIBRARY_PATH in the readme file and fixed the DB2 decimal column type error

Fixed 141 & 144 git issues

---

pooling.go

Concurrent map write on the Pool.availablePool and Pool.usedPool maps #117

Updated concurrent map write on the pool

---

README.md

Support for Golang version 1.17 #153

Support for Golang version 1.17

---

installer/setenv.sh

Script file to set environment variables only for non-Windows platform.
Add script to set environment variables #140

Script file to set environment variables

---

README.md

Updated README.md file for Docker Linux Container commands and install go_ibm_db command for Go Version >=1.17.x

Updated README.md file for Docker Linux Container commands

---

README.md

Support for Golang version 1.18

Support for Golang version 1.18

---

stmt.go
testdata/execContext_test.go
testdata/main.go
testdata/prepareContext_test.go
testdata/queryContext_test.go

Added PrepareContext, QueryContext and ExecContext methods and Test cases.

Added PrepareContext, QueryContext and ExecContext methods and Test cases.

---

README.md
installer/setenv.sh
installer/setup.go

Changed environment variable name DB2HOME to IBM_DB_HOME

Changed environment variable name DB2HOME to IBM_DB_HOME

---

README.md
installer/setenv.sh
installer/setup.go

Document Changes

---

README.md
installer/setenvwin.bat
installer/setup.go
testdata/main.go

Code Change in handling of os.LookupEnv

Change in handling of os.LookupEnv

---

README.md
stmt.go

Updated  ExecContext and QueryContext functions signature.

Updated ExecContext and QueryContext functions

---

testdata/alldatatypes_test.go
testdata/badconnectionstring_test.go
testdata/chinesechar_test.go
testdata/createdroptable_test.go
testdata/main.go
testdata/multiplequery_test.go
testdata/querycreatedroptable_test.go
testdata/queryinsertselect_test.go

Added new testcases

---

utf16.go

Fix issue #200 index out of range

---

README.md
installer/setup.go

Added db2level check before installing clidriver

Added db2level check before installing clidriver

---

INSTALL.md
testdata/Codeunits32_test.go
testdata/main.go
testdata/spArray_test.go

Added INSTALL.md file and new testcases for stored procedure using array and  char datatype (string) using Codeuints32 keyword.

Added INSTALL.md file and new testcases

---

LICENSE.md
README.md
api/api_zos.go
api/zapi_zos.go
conn.go
error.go

This commit fixes the README files with special attention instructions and sample code along with useful comments.
All recently changed and created files have also had their copyright years updated.
Spacing in files has also changed to make them easier to read.

Cleanup Files and README

---

README.md
testdata/createdroptable_test.go
testdata/main.go

Support for logging

---

.github/workflows/go.yml
testdata/main.go

Update main.go file to create a table and insert values in the Pooling testcases.

Update Pooling testcases

---

README.md

Update READMD.md document.

---

API_DOCUMENTATION.md
result.go
stmt.go
testdata/LastInsertId_test.go

Added LastInsertId Api to returns the id for the row most recently inserted into a table and test case.

LastInsertId Api  and Test case
